//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class action
    {
        public int action_id { get; set; }
        public int issue_id { get; set; }
        public string action_description { get; set; }
        public int user_id { get; set; }
    
        public virtual issue issue { get; set; }
        public virtual user user { get; set; }
    }
}
