//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Requests
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public issue()
        {
            this.actions = new HashSet<action>();
            this.reminders = new HashSet<reminder>();
        }
    
        public int issue_id { get; set; }
        public int issue_type_id { get; set; }
        public string issue_title { get; set; }
        public string issue_description { get; set; }
        public string issue_creator_username { get; set; }
        public System.DateTime issue_date_created { get; set; }
        public bool issue_ongoing { get; set; }
        public string issuer_id { get; set; }
        public string issuer_name { get; set; }
        public string issuer_tel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<action> actions { get; set; }
        public virtual issue_types issue_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reminder> reminders { get; set; }
    }
}
